In [1]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 36.7 MB/s eta 0:00:00m eta 0:00:010:00:01

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [10]:
a = np.arange(6)
a1 = np.array([1, 2, 3, 4, 5])
print(a)
print([1, 2, 3, 4, 5])
print(a1)

[0 1 2 3 4 5]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


## 100아래 있는 3의 배수 뽑기

In [15]:
a3 = np.arange(3, 100, 3)
print(a3)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


## 1에서 부터 10아래 0.5씩 증가하는 숫자 

In [19]:
a4 = np.arange(1.3, 10, .5)
print(a4)

# lista = [i for i in range(1.3, 10, 0.5)] 불가능!

[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


TypeError: 'float' object cannot be interpreted as an integer

## ndarray 만드는 다른방법

In [22]:
a5 = np.linspace(0, 10, 15) # 예외적으로 start 와 end 를 다 포함한다.
print(a5)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [28]:
a6 = np.zeros(5)
print(a6)

a7 = np.ones(5, dtype = np.int64)
print(a7)

a7.astype(np.float64)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [30]:
lista = [1, 2, 3.5, 4.2]

a8 = np.array(lista)
print(a8)

listb = [1, 2, 'abc', 'def']
a9 = np.array(listb)
print(a9)


[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']


In [32]:
a9.dtype

dtype('<U21')

In [38]:
print(a8.dtype)
print(a8.ndim) # n dimention 몇 차원이냐
print(a8.shape) # 생긴 모양 튜플로 반환
print(a8.size) # 배열안의 모든 element의 갯수

print(a8.itemsize) # 자료형의 사이즈
print(a8.data) # 메모리 주소

float64
1
(4,)
4
8


In [39]:
a10 = np.arange(10, 100, 5)
print(a10)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


## 위의 a10을 사용해서 인덱스 슬라이싱

In [43]:
print('특정 인덱스:', a10[5])

특정 인덱스: 35


In [41]:
print('스타트, 스탑:', a10[2:7])

스타트, 스탑: [20 25 30 35 40]


In [44]:
print('스타트, 스탑, 스텝:', a10[2:-2:2])

스타트, 스탑, 스텝: [20 30 40 50 60 70 80]


# 여러개의 인덱스를 한번에 주는법

In [48]:
print('1번째, 6번째, 9번째 인덱스값:', a10[[1, 6, 9]])

1번째, 6번째, 9번째 인덱스값: [15 40 55]


## 인덱스 안에 조건을 줄 수 있다.

In [49]:
print('10으로 나누어서 나머지가 5인 것들:', a10[a10 % 10 == 5])

10으로 나누어서 나머지가 5인 것들: [15 25 35 45 55 65 75 85 95]


## 리스트의 더하기와 ndarray에서의 더하기

In [50]:
lista = [x for x in range(3)]
listb = [x for x in range(10, 15)]

print(lista + listb)

[0, 1, 2, 10, 11, 12, 13, 14]


## numpy 에서는 각각의 인덱스 번호의 아이들 끼리 연산이 이루어진다

### 리스트 에서 처럼 그냥 크기를 늘려 이어 붙이기 위해서는 concatenate를 쓰고 함수안에는 튜플형식이 들어온다

### 리스트에서는 리스트끼리 빼기가 불가능하지만 numpy의 ndarray는 연산이 되기에 가능하다

#### 인덱스의 갯수가 맞지 않으면 연산이 불가능하다.

In [56]:
a1 = np.arange(5)
a2 = np.arange(10,15)
print(a1)
print(a2)
print('a1 add a2:', a1 + a2)
print('a1 subscribe a2:', a1 - a2)
print('a1 multiple a2:', a1 * a2)
print('a1 division a2:', a1 / a2)

print(np.concatenate((a1, a2)))



[0 1 2 3 4 5 6]
[10 11 12 13 14]


ValueError: operands could not be broadcast together with shapes (7,) (5,) 