In [26]:
import requests
import numpy as np
x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [27]:
raw_data = []
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
    
for sample in raw_data:
    if len(sample) < 1 :
        continue
    for i, value in enumerate(sample[:4]):
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0

In [28]:
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


In [29]:
for i in raw_data:
    if len(i) < 2:
        continue
    if i[-1] in 'Iris-setosa':
        i[-1] = 0.0
    elif i[-1] in 'Iris-versicolor':
        i[-1] = 1.0
    elif i[-1] in 'Iris-virginica':
        i[-1] = 2.0

In [32]:
print(len(raw_data))
raw_data = raw_data[:150]

152


In [33]:
print(len(raw_data))

150


In [50]:
np_data = np.array(raw_data)
np_data.shape
np_data[149]


array([5.9, 3. , 5.1, 1.8, 2. ])

## 기본 통계값

 - 전체평균, 표준편차 - sepal length, sepal width, petal length, petal width
 - 품종별 평균, 표준편차
 
 - 평균 np.mean()
 - 표준편차 np.std()

In [62]:
print(np.min(np_data[:, :-1], axis = 0))
print(np.max(np_data[:, :-1], axis = 0))
print(np.mean(np_data[:, :-1], axis = 0))
print(np.std(np_data[:, :-1], axis = 0))
print(np.corrcoef(np_data.T)) # 상관도

[4.3 2.  1.  0.1]
[7.9 4.4 6.9 2.5]
[5.84333333 3.054      3.75866667 1.19866667]
[0.82530129 0.43214658 1.75852918 0.76061262]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [65]:
filter_setosa = np_data[:, -1] == 0
filter_versicolor = np_data[:, -1] == 1
filter_virginica = np_data[:, -1] == 2

print('setosa-min:', np.min(np_data[filter_setosa], axis = 0))
print('setosa-max:', np.max(np_data[filter_setosa], axis = 0))
print('setosa-mean:', np.mean(np_data[filter_setosa], axis = 0))
print('setosa-std:', np.std(np_data[filter_setosa], axis = 0))
print(np.corrcoef(np_data[filter_setosa].T))
print()
print('versicolor-min:', np.min(np_data[filter_versicolor], axis = 0))
print('versicolor-max:', np.max(np_data[filter_versicolor], axis = 0))
print('versicolor-mean:', np.mean(np_data[filter_versicolor], axis = 0))
print('versicolor-std:', np.std(np_data[filter_versicolor], axis = 0))
print(np.corrcoef(np_data[filter_versicolor].T))
print()
print('virginica-min:', np.min(np_data[filter_virginica], axis = 0))
print('virginica-max:', np.max(np_data[filter_virginica], axis = 0))
print('virginica-mean:', np.mean(np_data[filter_virginica], axis = 0))
print('virginica-std:', np.std(np_data[filter_virginica], axis = 0))
print(np.corrcoef(np_data[filter_virginica].T))

setosa-min: [4.3 2.3 1.  0.1 0. ]
setosa-max: [5.8 4.4 1.9 0.6 0. ]
setosa-mean: [5.006 3.418 1.464 0.244 0.   ]
setosa-std: [0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
[[1.         0.74678037 0.26387409 0.27909157        nan]
 [0.74678037 1.         0.17669463 0.27997289        nan]
 [0.26387409 0.17669463 1.         0.30630821        nan]
 [0.27909157 0.27997289 0.30630821 1.                nan]
 [       nan        nan        nan        nan        nan]]

versicolor-min: [4.9 2.  3.  1.  1. ]
versicolor-max: [7.  3.4 5.1 1.8 1. ]
versicolor-mean: [5.936 2.77  4.26  1.326 1.   ]
versicolor-std: [0.51098337 0.31064449 0.46518813 0.19576517 0.        ]
[[1.         0.52591072 0.75404896 0.54646107        nan]
 [0.52591072 1.         0.56052209 0.66399872        nan]
 [0.75404896 0.56052209 1.         0.78666809        nan]
 [0.54646107 0.66399872 0.78666809 1.                nan]
 [       nan        nan        nan        nan        nan]]

virginica-min: [4.9 2.2 4.5 1.4 2. ]

/opt/homebrew/Cellar/jupyterlab/3.4.8_1/libexec/lib/python3.11/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/opt/homebrew/Cellar/jupyterlab/3.4.8_1/libexec/lib/python3.11/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
