In [4]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(100, 110)
print(a1, a2)
print(a1 + a2)

a3 = np.array([5]*10)
print(a1 + a3)
print(a1 + 5)

[0 1 2 3 4 5 6 7 8 9] [100 101 102 103 104 105 106 107 108 109]
[100 102 104 106 108 110 112 114 116 118]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
# f(x) = 3x + 5
# x = 0 에서 100 사이 짝수일 때 f(x)의 합.

x = np.arange(0, 101, 2)

def f(a):
    return sum((3 * a) + 5)

print(f(x))

7905


In [8]:
a2 = np.arange(30).reshape(5,6)
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [9]:
a2 + 100

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129]])

In [11]:
a3 = np.arange(6)
print(a2 + a3)

[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]]


In [13]:
a4 = np.arange(100,130).reshape(5,6)
print(a4)

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]


In [15]:
a10 = np.arange(3 * 5 * 7 * 8).reshape(3,5,7,8)
print(a10.shape)

# 스칼라
#(8,)
#(7,8)
#(5,7,8)
#(3,5,7,8)

a5 = np.arange(56).reshape(7,8)

(3, 5, 7, 8)


In [16]:
a10 + a5

array([[[[  0,   2,   4,   6,   8,  10,  12,  14],
         [ 16,  18,  20,  22,  24,  26,  28,  30],
         [ 32,  34,  36,  38,  40,  42,  44,  46],
         [ 48,  50,  52,  54,  56,  58,  60,  62],
         [ 64,  66,  68,  70,  72,  74,  76,  78],
         [ 80,  82,  84,  86,  88,  90,  92,  94],
         [ 96,  98, 100, 102, 104, 106, 108, 110]],

        [[ 56,  58,  60,  62,  64,  66,  68,  70],
         [ 72,  74,  76,  78,  80,  82,  84,  86],
         [ 88,  90,  92,  94,  96,  98, 100, 102],
         [104, 106, 108, 110, 112, 114, 116, 118],
         [120, 122, 124, 126, 128, 130, 132, 134],
         [136, 138, 140, 142, 144, 146, 148, 150],
         [152, 154, 156, 158, 160, 162, 164, 166]],

        [[112, 114, 116, 118, 120, 122, 124, 126],
         [128, 130, 132, 134, 136, 138, 140, 142],
         [144, 146, 148, 150, 152, 154, 156, 158],
         [160, 162, 164, 166, 168, 170, 172, 174],
         [176, 178, 180, 182, 184, 186, 188, 190],
         [192, 194, 196, 19

## 문제
- axis1의 3개의 값 중 
    - 첫번째는 곱하기 2
    - 두번째는 곱하기 10
    - 세번째는 곱하기 12
- axis1을 따라 합계 구하기

In [29]:
a15 = np.arange(15).reshape(5,3)
a2 = np.array([2,10,12])
a20 = np.multiply(a15,a2)

a25 = np.sum(a20, axis=1)
print(a15)
print(a20)
print(a25)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[  0  10  24]
 [  6  40  60]
 [ 12  70  96]
 [ 18 100 132]
 [ 24 130 168]]
[ 34 106 178 250 322]
